### ISSUE TITLE
Plus de possibilité de commit/pull/push

### ISSUE THREAD

**Issue by AimericVandescure** [AimericVandescure/aimeric-vandescure-blog#1]
Bonsoir, désolé de vous déranger mais je n'arrive pas à réaliser de commit ni de pull ni de push pour mon blog, en effet comme vous pouvez le voir ces sections sont grisées et je ne comprend pas pourquoi, pouvez vous m'aider ?
![image](https://user-images.githubusercontent.com/55579036/67977297-1bf58280-fc18-11e9-84c1-a34c16cabf57.png)

**Comment by GuyliannEngels** [comment]
Salut @AimericVandescure ,

Je viens de voir un mail de toi, est ce que ce mail est relatif à cette issue ?

**Comment by AimericVandescure** [comment]
Bonsoir, oui désolé mes mails ont du mal à charger parfois et laissent seulement ceux de la semaine dernière, du coup j'ai réussi à remettre ça en place en supprimant le dossier rmd qui bloquait, bonne soirée

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________
